common:
    lid_topic:  "/livox/lidar"

preprocess:
    lidar_type: 1                # Livox
    feature_extract_en: false
    scan_line: 6
    blind: 1
    point_filter_num: 3

initialization:
    cut_frame: true
    cut_frame_num: 6           # 分帧数
    cut_frame_init_num: 5       # 如果分帧的话 从第几帧开始分帧 默认固态 5 机械 20

mapping:
    filter_size_surf: 0.3
    filter_size_map: 0.3
    gyr_cov: 1.01               # 角速度噪声协方差
    acc_cov: 1.01               # 线速度噪声协方差
    det_range: 100.0
    cov_lidar: 0.001            # 雷达观测噪声协方差
    max_iteration: 20           # iekf最大迭代次数
    max_undistort: 5            # 最大去畸变次数  与 最大迭代次数 二者达到一个即退出迭代
    cube_side_length: 2000

publish:
    path_en:  true
    scan_publish_en:  true
    dense_publish_en: true
    scan_bodyframe_pub_en: false

pcd_save:
    pcd_save_en: false
    interval: -1

