common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1                # Livox series LiDAR
    feature_extract_en: false
    scan_line: 6
    blind: 1

initialization:
    cut_frame: false
    cut_frame_num: 5            # must be positive integer
    orig_odom_freq: 10           # original Lidar frequency
    mean_acc_norm: 9.805         # 1 for livox built-in IMU
    online_refine_time: 20     # seconds
    data_accum_length: 500
    Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
    Trans_LI_cov: [ 0.00001, 0.00001, 0.00001 ]

mapping:
    filter_size_surf: 0.5
    filter_size_map: 0.5
    scale_mid: 1
    scale_big: 1
    gyr_cov: 50
    acc_cov: 50
    b_acc_cov: 0.0001 # 0.0001
    b_gyr_cov: 0.0001
    det_range: 100.0
    imu_en: false
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
    extrinsic_R: [ 1, 0, 0,
                       0, 1, 0,
                       0, 0, 1 ]
    undistort_iter: false
    cov_lidar: 0.001

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file;
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
